export const AVATAR_STATES = ["IDLE","LISTENING","THINKING","WORKING","SPEAKING","SUCCESS","WARNING","ERROR","SEARCHING","READING","MEMORY_RECALL","CODING","RUNNING_TESTS","BROWSING","WAITING","CONFUSED","EXCITED","GESTURING"] as const;
export type AvatarState = (typeof AVATAR_STATES)[number];
export type SemanticState = AvatarState;
export const LOCOMOTION_STATES = ["STANDING","WALKING","RUNNING","TURNING","ROLLING","CROUCHING"] as const;
export type LocomotionState = (typeof LOCOMOTION_STATES)[number];
export type AvatarExpression = "neutral" | "happy" | "concerned" | "confused" | "focused" | "surprised" | "excited";
export type AvatarGazeTarget = "USER" | "CHAT_PANEL" | "RESULTS_PANEL" | "CODE_PANEL" | "BROWSER_PANEL" | "NOTIFICATION" | "CUSTOM_POINT";
export interface AvatarPosition { x: number; z: number; }
export interface AvatarSnapshot { state: AvatarState; semanticState: SemanticState; locomotionState: LocomotionState; expression: AvatarExpression; expressionIntensity: number; gazeTarget: AvatarGazeTarget; speaking: boolean; mouthOpen: number; visible: boolean; modelStatus: "loading" | "ready" | "unavailable" | "error"; position: AvatarPosition; targetPosition: AvatarPosition; facing: number; speed: number; action?: string; lastEvent?: string; error?: string; }
export interface AvatarAdapter { setState(state: AvatarState): void; setExpression(expression: AvatarExpression, intensity: number): void; setGazeTarget(target: AvatarGazeTarget): void; setSpeaking(speaking: boolean): void; updateLipSync(openness: number): void; playGesture(name: string): boolean; setLocomotion(state: LocomotionState): void; setTargetPosition(position: AvatarPosition): void; update(deltaSeconds: number): void; dispose(): void; }
export const DEFAULT_AVATAR_SNAPSHOT: AvatarSnapshot = { state: "IDLE", semanticState: "IDLE", locomotionState: "STANDING", expression: "neutral", expressionIntensity: 1, gazeTarget: "USER", speaking: false, mouthOpen: 0, visible: true, modelStatus: "loading", position: { x: 0, z: 0 }, targetPosition: { x: 0, z: 0 }, facing: 0, speed: 0 };
function finite(value: unknown, fallback: number): number { return typeof value === "number" && Number.isFinite(value) ? value : fallback; }
export function normalizeAvatarSnapshot(value: unknown): AvatarSnapshot { const input = (value && typeof value === "object" ? value : {}) as Record<string, unknown>; const state = AVATAR_STATES.includes(input.state as AvatarState) ? input.state as AvatarState : "IDLE"; const semanticState = AVATAR_STATES.includes(input.semanticState as SemanticState) ? input.semanticState as SemanticState : state; const locomotionState = LOCOMOTION_STATES.includes(input.locomotionState as LocomotionState) ? input.locomotionState as LocomotionState : "STANDING"; const position = (input.position && typeof input.position === "object" ? input.position : {}) as Record<string, unknown>; const target = (input.targetPosition && typeof input.targetPosition === "object" ? input.targetPosition : {}) as Record<string, unknown>; return { ...DEFAULT_AVATAR_SNAPSHOT, ...input, state, semanticState, locomotionState, position: { x: finite(position.x, 0), z: finite(position.z, 0) }, targetPosition: { x: finite(target.x, finite(position.x, 0)), z: finite(target.z, finite(position.z, 0)) }, facing: finite(input.facing, 0), speed: Math.max(0, finite(input.speed, 0)), expressionIntensity: finite(input.expressionIntensity, 1), mouthOpen: Math.max(0, Math.min(1, finite(input.mouthOpen, 0))), visible: input.visible !== false, speaking: Boolean(input.speaking), modelStatus: (input.model_status ?? input.modelStatus ?? "loading") as AvatarSnapshot["modelStatus"], lastEvent: typeof input.lastEvent === "string" ? input.lastEvent : undefined, error: typeof input.error === "string" ? input.error : undefined }; }
