"""World Model Package.

This package provides Freya's unified view of its operating environment,
integrating all environment layers into a single facade.
"""

from app.world_model.model import (
    EnvironmentSnapshot,
    ProjectInfo,
    RuntimeInfo,
    GitInfo,
    ResourceInfo,
    ToolInfo,
    HealthInfo,
    WorldModel,
    create_world_model,
)
from app.world_model.retrieval import (
    TaskContext,
    get_relevant_context,
    filter_snapshot_for_task,
    get_relevant_summary,
    list_supported_task_types,
    get_task_type_description,
    init_learned_relevance,
    record_retrieval_outcome,
    get_learned_relevance_summary,
    get_all_learned_relevance,
    reset_learned_relevance,
)
from app.world_model.learned_relevance import (
    LearnedRelevanceEngine,
    TaskRelevanceWeights,
    RetrievalOutcome,
    create_learned_relevance_engine,
)
from app.world_model.project_metadata import (
    ProjectMetadata,
    DependencyInfo,
    DependencySet,
    ProjectDependencies,
    ProjectMetadataParser,
    DependencyParser,
    detect_project_metadata,
    detect_dependencies,
    detect_full_project,
    enhance_world_model_with_project_data,
)

__all__ = [
    "EnvironmentSnapshot",
    "ProjectInfo",
    "RuntimeInfo",
    "GitInfo",
    "ResourceInfo",
    "ToolInfo",
    "HealthInfo",
    "WorldModel",
    "create_world_model",
    "TaskContext",
    "get_relevant_context",
    "filter_snapshot_for_task",
    "get_relevant_summary",
    "list_supported_task_types",
    "get_task_type_description",
    "init_learned_relevance",
    "record_retrieval_outcome",
    "get_learned_relevance_summary",
    "get_all_learned_relevance",
    "reset_learned_relevance",
    "LearnedRelevanceEngine",
    "TaskRelevanceWeights",
    "RetrievalOutcome",
    "create_learned_relevance_engine",
    "ProjectMetadata",
    "DependencyInfo",
    "DependencySet",
    "ProjectDependencies",
    "ProjectMetadataParser",
    "DependencyParser",
    "detect_project_metadata",
    "detect_dependencies",
    "detect_full_project",
    "enhance_world_model_with_project_data",
]