"""Data models for Long-Term Autonomy."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional
from uuid import uuid4


@dataclass
class AutonomyStateData:
    """Overall state of the autonomous system."""
    is_running: bool = False
    is_initialized: bool = False
    last_heartbeat: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    startup_time: Optional[str] = None
    shutdown_time: Optional[str] = None
    current_phase: str = ""  # e.g., "observation", "decision", "execution", "verification", "learning"
    cycle_count: int = 0
    error_count: int = 0
    warning_count: int = 0
    active_tasks_count: int = 0
    completed_tasks_count: int = 0
    failed_tasks_count: int = 0
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class AutonomousTask:
    """Represents a task generated by the autonomous system."""
    id: str = field(default_factory=lambda: f"auto_task_{uuid4().hex[:8]}")
    description: str = ""
    source: str = ""  # e.g., "decision_loop", "self_initiated", "maintenance"
    priority: int = 1  # 1=low, 2=medium, 3=high
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    scheduled_for: Optional[str] = None
    deadline: Optional[str] = None
    dependencies: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: str = "pending"  # pending, scheduled, running, completed, failed, cancelled
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    retry_count: int = 0
    max_retries: int = 3


@dataclass
class AutonomyConfig:
    """Configuration for the autonomous system."""
    # General settings
    enabled: bool = True
    max_concurrent_tasks: int = 5
    cycle_interval_seconds: float = 30.0  # How often the autonomy loop runs
    heartbeat_interval_seconds: float = 10.0

    # Observation settings
    observation_enabled: bool = True
    observation_sources: List[str] = field(default_factory=lambda: [
        "system_metrics", "goal_status", "task_status", "resource_usage"
    ])

    # Decision settings
    decision_enabled: bool = True
    decision_strategy: str = "weighted_scoring"  # e.g., "weighted_scoring", "priority_based", "learning_based"
    min_decision_confidence: float = 0.3

    # Execution settings
    execution_enabled: bool = True
    task_timeout_seconds: float = 300.0  # 5 minutes default
    max_retries_per_task: int = 3

    # Verification settings
    verification_enabled: bool = True
    verification_timeout_seconds: float = 60.0

    # Learning settings
    learning_enabled: bool = True
    learning_interval_cycles: int = 5  # Learn every N cycles

    # Maintenance settings
    maintenance_enabled: bool = True
    maintenance_interval_hours: float = 24.0  # Daily maintenance

    # Recovery settings
    recovery_enabled: bool = True
    max_consecutive_failures: int = 5
    failure_backoff_base_seconds: float = 5.0

    # Persistence settings
    state_persistence_enabled: bool = True
    state_persistence_interval_seconds: float = 60.0

    # Logging settings
    log_level: str = "INFO"
    log_cycle_details: bool = False

    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# Reusing models from the previous step for completeness
@dataclass
class ObservationData:
    """Data collected during the observation phase."""
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    system_metrics: Dict[str, Any] = field(default_factory=dict)
    goal_status: Dict[str, Any] = field(default_factory=dict)
    task_status: Dict[str, Any] = field(default_factory=dict)
    resource_usage: Dict[str, Any] = field(default_factory=dict)
    external_events: List[Dict[str, Any]] = field(default_factory=list)
    anomalies: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class DecisionOutput:
    """Output from the decision phase."""
    decision_id: str = field(default_factory=lambda: f"decision_{uuid4().hex[:8]}")
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    action_type: str = ""  # e.g., "execute_task", "create_goal", "modify_goal", "maintenance"
    action_details: Dict[str, Any] = field(default_factory=dict)
    priority: int = 1
    confidence: float = 0.0  # 0.0 to 1.0
    reasoning: str = ""
    expected_outcome: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LearningUpdate:
    """Update from the learning phase."""
    update_id: str = field(default_factory=lambda: f"learning_{uuid4().hex[:8]}")
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    update_type: str = ""  # e.g., "pattern_discovered", "strategy_updated", "model_updated"
    description: str = ""
    data: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0